// AEGIS/client/src/components/chat/ChatMessage.tsx
import React from 'react';

import { ChatMessage as ChatMessageType } from '../../types';

interface ChatMessageProps {
    message: ChatMessageType;
}

const ChatMessage: React.FC<ChatMessageProps> = ({ message }) => {
    return (
        <article className={`chat-message chat-message--${message.role}`}>
            <header className="chat-message__role">{message.role}</header>
            <p className="chat-message__content">{message.content}</p>
        </article>
    );
};

export default ChatMessage;

// app/client/src/app/components/chat-message.component.ts
import { Component, Input } from '@angular/core';

import { ChatMessage } from '../core/types';

@Component({
  selector: 'article[appChatMessage]',
  standalone: true,
  templateUrl: './chat-message.component.html',
  host: {
    class: 'chat-message',
    '[class]': "'chat-message chat-message--' + message.role + (message.kind ? ' chat-message--' + message.kind : '')",
  },
})
export class ChatMessageComponent {
  @Input({ required: true }) message!: ChatMessage;
}

<header class="chat-message__role">{{ message.kind === 'steering' ? 'Refinement' : message.role }}</header>
<p class="chat-message__content">{{ message.content }}</p>
