// AEGIS/client/src/components/MapPreview.tsx
import React, { useEffect, useMemo, useRef, useState } from 'react';
import maplibregl, { LngLatBoundsLike, Map, StyleSpecification } from 'maplibre-gl';

import {
    DEFAULT_BASE_ATTRIBUTION,
    DEFAULT_BASE_TILE_URL,
    DEFAULT_OVERLAY_OPACITY,
    DEFAULT_WMS_EXCEPTIONS,
    DEFAULT_WMS_LAYER_ID,
    DEFAULT_WMS_VERSION,
    DEFAULT_WMTS_FORMAT,
    DEFAULT_WMTS_MATRIX_SET,
} from '../constants';
import { MapSession, SearchResponsePayload } from '../types';
import './MapPreview.css';

interface MapPreviewProps {
    payload?: SearchResponsePayload;
    isLoading: boolean;
    emptyMessage?: string;
    initialOverlayVisibility?: Record<string, boolean>;
    initialOverlayOpacity?: Record<string, number>;
    onOverlayStateChange?: (state: {
        overlayVisibility: Record<string, boolean>;
        overlayOpacity: Record<string, number>;
    }) => void;
}

type OverlayEntry = NonNullable<MapSession['overlays']>[number];

const appendQuery = (baseUrl: string, query: string): string => {
    const separator = baseUrl.includes('?') ? '&' : '?';
    return `${baseUrl}${separator}${query}`;
};

const normalizeOverlayBounds = (
    bounds?: [number, number, number, number],
): [number, number, number, number] | undefined => {
    if (!Array.isArray(bounds) || bounds.length !== 4) {
        return undefined;
    }
    const [minLon, minLat, maxLon, maxLat] = bounds;
    return [minLon, minLat, maxLon, maxLat];
};

const buildWmsTileUrl = (overlay: OverlayEntry): string | null => {
    if (!overlay.url) {
        return null;
    }
    const layers = overlay.layers || DEFAULT_WMS_LAYER_ID;
    const version = overlay.wms_version || DEFAULT_WMS_VERSION;
    const exceptions = overlay.wms_exceptions || DEFAULT_WMS_EXCEPTIONS;
    const query = [
        'service=WMS',
        'request=GetMap',
        `layers=${encodeURIComponent(layers)}`,
        'styles=',
        'format=image/png',
        'transparent=true',
        `version=${encodeURIComponent(version)}`,
        'srs=EPSG:3857',
        `exceptions=${encodeURIComponent(exceptions)}`,
        'bbox={bbox-epsg-3857}',
        'width=256',
        'height=256',
    ].join('&');
    return appendQuery(overlay.url, query);
};

const buildWmtsTileUrl = (overlay: OverlayEntry): string | null => {
    if (!overlay.url) {
        return null;
    }
    const layerId = overlay.layer_id || overlay.layers || DEFAULT_WMS_LAYER_ID;
    const matrixSet = overlay.tile_matrix_set || DEFAULT_WMTS_MATRIX_SET;
    const format = overlay.wmts_format || DEFAULT_WMTS_FORMAT;
    const style = overlay.wmts_style ?? '';
    const query = [
        'service=WMTS',
        'request=GetTile',
        'version=1.0.0',
        `layer=${encodeURIComponent(layerId)}`,
        `style=${encodeURIComponent(style)}`,
        `tilematrixset=${encodeURIComponent(matrixSet)}`,
        `tilematrix=${matrixSet}:{z}`,
        'tilerow={y}',
        'tilecol={x}',
        `format=${encodeURIComponent(format)}`,
    ].join('&');
    return appendQuery(overlay.url, query);
};

const buildStyle = (mapSession?: MapSession): StyleSpecification => {
    const basemap = mapSession?.basemap;
    const baseTileUrl = basemap?.tile_url || DEFAULT_BASE_TILE_URL;
    return {
        version: 8,
        sources: {
            basemap: {
                type: 'raster',
                tiles: [baseTileUrl],
                tileSize: 256,
                attribution: basemap?.attribution || DEFAULT_BASE_ATTRIBUTION,
            },
        },
        layers: [
            {
                id: 'basemap',
                type: 'raster',
                source: 'basemap',
                minzoom: 0,
                maxzoom: 22,
            },
        ],
    };
};

const addOverlayLayers = (map: Map, mapSession?: MapSession) => {
    const overlays = mapSession?.overlays || [];
    overlays.forEach((overlay, index) => {
        const sourceId = `overlay-source-${overlay.id}`;
        const layerId = `overlay-layer-${overlay.id}`;
        const opacity = typeof overlay.default_opacity === 'number' ? overlay.default_opacity : DEFAULT_OVERLAY_OPACITY;
        const sourceBounds = normalizeOverlayBounds(overlay.bounds);

        if (overlay.type === 'tile' && overlay.url) {
            const rasterSource: {
                type: 'raster';
                tiles: string[];
                tileSize: number;
                bounds?: [number, number, number, number];
            } = {
                type: 'raster',
                tiles: [overlay.url],
                tileSize: 256,
            };
            if (sourceBounds) {
                rasterSource.bounds = sourceBounds;
            }
            map.addSource(sourceId, rasterSource);
            map.addLayer({
                id: layerId,
                source: sourceId,
                type: 'raster',
                paint: { 'raster-opacity': opacity },
            });
            return;
        }

        if (overlay.type === 'wms' && overlay.url) {
            const wmsTiles = buildWmsTileUrl(overlay);
            if (!wmsTiles) {
                return;
            }
            const rasterSource: {
                type: 'raster';
                tiles: string[];
                tileSize: number;
                bounds?: [number, number, number, number];
            } = {
                type: 'raster',
                tiles: [wmsTiles],
                tileSize: 256,
            };
            if (sourceBounds) {
                rasterSource.bounds = sourceBounds;
            }
            map.addSource(sourceId, rasterSource);
            map.addLayer({
                id: layerId,
                source: sourceId,
                type: 'raster',
                paint: { 'raster-opacity': opacity },
            });
            return;
        }

        if (overlay.type === 'wmts' && overlay.url) {
            const wmtsTiles = buildWmtsTileUrl(overlay);
            if (!wmtsTiles) {
                return;
            }
            const rasterSource: {
                type: 'raster';
                tiles: string[];
                tileSize: number;
                bounds?: [number, number, number, number];
            } = {
                type: 'raster',
                tiles: [wmtsTiles],
                tileSize: 256,
            };
            if (sourceBounds) {
                rasterSource.bounds = sourceBounds;
            }
            map.addSource(sourceId, rasterSource);
            map.addLayer({
                id: layerId,
                source: sourceId,
                type: 'raster',
                paint: { 'raster-opacity': opacity },
            });
            return;
        }

        if (overlay.type === 'point-insight') {
            const center = mapSession?.center;
            if (typeof center?.longitude !== 'number' || typeof center?.latitude !== 'number') {
                return;
            }
            map.addSource(sourceId, {
                type: 'geojson',
                data: {
                    type: 'FeatureCollection',
                    features: [
                        {
                            type: 'Feature',
                            properties: { label: overlay.label },
                            geometry: {
                                type: 'Point',
                                coordinates: [center.longitude, center.latitude],
                            },
                        },
                    ],
                },
            });
            map.addLayer({
                id: layerId,
                source: sourceId,
                type: 'circle',
                paint: {
                    'circle-radius': 8 + index,
                    'circle-color': '#ef4444',
                    'circle-opacity': opacity,
                    'circle-stroke-width': 1,
                    'circle-stroke-color': '#111827',
                },
            });
        }
    });
};

const normalizeBounds = (bounds?: number[]): LngLatBoundsLike | null => {
    if (!Array.isArray(bounds) || bounds.length !== 4) {
        return null;
    }
    const [minx, miny, maxx, maxy] = bounds;
    return [[minx, miny], [maxx, maxy]];
};

const MapPreview: React.FC<MapPreviewProps> = ({
    payload,
    isLoading,
    emptyMessage = 'Run a search to display the map.',
    initialOverlayVisibility = {},
    initialOverlayOpacity = {},
    onOverlayStateChange,
}) => {
    const mapContainerRef = useRef<HTMLDivElement | null>(null);
    const mapRef = useRef<Map | null>(null);
    const mapSession = payload?.map_session;
    const [overlayVisibility, setOverlayVisibility] = useState<Record<string, boolean>>(initialOverlayVisibility);
    const [overlayOpacity, setOverlayOpacity] = useState<Record<string, number>>(initialOverlayOpacity);
    const [restoreNotice, setRestoreNotice] = useState('');
    const hasCenter = useMemo(() => {
        return typeof mapSession?.center?.latitude === 'number' && typeof mapSession?.center?.longitude === 'number';
    }, [mapSession]);

    useEffect(() => {
        const overlays = mapSession?.overlays || [];
        const overlayIds = new Set(overlays.map((overlay) => overlay.id));
        const staleVisibilityKeys = Object.keys(initialOverlayVisibility).filter((key) => !overlayIds.has(key));
        const staleOpacityKeys = Object.keys(initialOverlayOpacity).filter((key) => !overlayIds.has(key));
        const staleIds = new Set([...staleVisibilityKeys, ...staleOpacityKeys]);
        if (staleIds.size > 0) {
            setRestoreNotice(
                `Some saved overlay preferences could not be restored (${staleIds.size} removed or unknown overlay id${staleIds.size === 1 ? '' : 's'}).`,
            );
        } else {
            setRestoreNotice('');
        }
        setOverlayVisibility((current) => {
            const next: Record<string, boolean> = {};
            overlays.forEach((overlay) => {
                next[overlay.id] = current[overlay.id] ?? initialOverlayVisibility[overlay.id] ?? true;
            });
            return next;
        });
        setOverlayOpacity((current) => {
            const next: Record<string, number> = {};
            overlays.forEach((overlay) => {
                const fallback = typeof overlay.default_opacity === 'number' ? overlay.default_opacity : DEFAULT_OVERLAY_OPACITY;
                next[overlay.id] = current[overlay.id] ?? initialOverlayOpacity[overlay.id] ?? fallback;
            });
            return next;
        });
    }, [mapSession, initialOverlayVisibility, initialOverlayOpacity]);

    useEffect(() => {
        if (!onOverlayStateChange) {
            return;
        }
        onOverlayStateChange({ overlayVisibility, overlayOpacity });
    }, [overlayVisibility, overlayOpacity, onOverlayStateChange]);

    useEffect(() => {
        if (!mapContainerRef.current || !hasCenter || !mapSession?.center) {
            return;
        }
        if (mapRef.current) {
            mapRef.current.remove();
            mapRef.current = null;
        }
        const map = new maplibregl.Map({
            container: mapContainerRef.current,
            style: buildStyle(mapSession),
            center: [mapSession.center.longitude!, mapSession.center.latitude!],
            zoom: 12,
        });
        map.addControl(new maplibregl.NavigationControl({ showCompass: true }), 'top-right');
        map.on('load', () => {
            addOverlayLayers(map, mapSession);
            const bounds = normalizeBounds(mapSession.bounds);
            if (bounds) {
                map.fitBounds(bounds, { padding: 30, duration: 0 });
            }
        });
        mapRef.current = map;
        return () => {
            map.remove();
            mapRef.current = null;
        };
    }, [mapSession, hasCenter]);

    useEffect(() => {
        const map = mapRef.current;
        if (!map || !mapSession?.overlays?.length) {
            return;
        }
        mapSession.overlays.forEach((overlay) => {
            const layerId = `overlay-layer-${overlay.id}`;
            if (!map.getLayer(layerId)) {
                return;
            }
            const visible = overlayVisibility[overlay.id] ?? true;
            map.setLayoutProperty(layerId, 'visibility', visible ? 'visible' : 'none');
            const opacityValue = overlayOpacity[overlay.id] ?? overlay.default_opacity ?? DEFAULT_OVERLAY_OPACITY;
            if (overlay.type === 'point-insight') {
                map.setPaintProperty(layerId, 'circle-opacity', opacityValue);
            } else {
                map.setPaintProperty(layerId, 'raster-opacity', opacityValue);
            }
        });
    }, [mapSession, overlayVisibility, overlayOpacity]);

    const renderContent = () => {
        if (isLoading) {
            return (
                <div className="spinner-container">
                    <div className="animate-spin rounded-full h-12 w-12 border-4 border-primary/20 border-t-primary"></div>
                    <p className="loading-text">Rendering map...</p>
                </div>
            );
        }
        if (!payload || (!payload.satellite_imagery && !payload.map_session)) {
            return <div className="empty-state">{emptyMessage}</div>;
        }
        if (!hasCenter) {
            return <div className="empty-state">Map center unavailable for interactive rendering.</div>;
        }
        return (
            <div className="maplibre-wrap">
                <div ref={mapContainerRef} className="maplibre-container" />
                {!!mapSession?.overlays?.length && (
                    <div className="overlay-controls">
                        {mapSession.overlays.map((overlay) => (
                            <div key={overlay.id} className="overlay-control-row">
                                <label>
                                    <input
                                        type="checkbox"
                                        checked={overlayVisibility[overlay.id] ?? true}
                                        onChange={(event) => {
                                            setOverlayVisibility((current) => ({
                                                ...current,
                                                [overlay.id]: event.target.checked,
                                            }));
                                        }}
                                    />
                                    {overlay.label}
                                </label>
                                <input
                                    type="range"
                                    min={0}
                                    max={100}
                                    value={Math.round((overlayOpacity[overlay.id] ?? overlay.default_opacity ?? DEFAULT_OVERLAY_OPACITY) * 100)}
                                    onChange={(event) => {
                                        const value = Number(event.target.value) / 100;
                                        setOverlayOpacity((current) => ({
                                            ...current,
                                            [overlay.id]: value,
                                        }));
                                    }}
                                />
                            </div>
                        ))}
                    </div>
                )}
                {!!mapSession?.compliance_warnings?.length && (
                    <div className="compliance-panel">
                        {mapSession.compliance_warnings.map((warning) => (
                            <p key={warning}>{warning}</p>
                        ))}
                    </div>
                )}
                {!!restoreNotice && (
                    <div className="compliance-panel" role="status" aria-live="polite">
                        <p>{restoreNotice}</p>
                    </div>
                )}
            </div>
        );
    };

    return (
        <div className="map-canvas">
            <div className="map-content">
                {renderContent()}
            </div>
        </div>
    );
};

export default MapPreview;

// app/client/src/app/components/map-preview.component.ts
import {
  AfterViewInit,
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  SimpleChanges,
  ViewChild,
  ChangeDetectionStrategy
} from '@angular/core';
import maplibregl, { Map } from 'maplibre-gl';

import { DEFAULT_MAP_FIT_MAX_ZOOM, DEFAULT_OVERLAY_OPACITY } from '../core/constants';
import {
  MapSession,
  OverlayRenderStatus,
  OverlayOpacityChange,
  OverlayStateChange,
  OverlayVisibilityChange,
  SearchResponsePayload,
} from '../core/types';
import { OverlayControlsComponent } from './overlay-controls.component';
import {
  OverlayEntry,
  addOverlayLayers,
  buildStyle,
  isGeoJsonOverlay,
  normalizeBounds,
  recordBooleanEqual,
  recordNumberEqual,
  removeOverlayLayers,
} from './map-preview-rendering';

export type MapRenderState = 'preparing' | 'ready' | 'failed';

export interface MapRenderStateChange {
  sessionId: string;
  state: MapRenderState;
  message?: string;
}

@Component({
  selector: 'app-map-preview',
  standalone: true,
  imports: [OverlayControlsComponent],
  templateUrl: './map-preview.component.html',
  changeDetection: ChangeDetectionStrategy.Eager,
  styleUrl: './map-preview.component.css',
})
export class MapPreviewComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() payload?: SearchResponsePayload;
  @Input() isLoading = false;
  @Input() emptyMessage = 'Run a search to display the map.';
  @Input() initialOverlayVisibility: Record<string, boolean> = {};
  @Input() initialOverlayOpacity: Record<string, number> = {};
  @Output() overlayStateChange = new EventEmitter<OverlayStateChange>();
  @Output() renderStateChange = new EventEmitter<MapRenderStateChange>();

  @ViewChild('mapContainer', { static: false })
  private set mapContainer(value: ElementRef<HTMLDivElement> | undefined) {
    this.mapContainerRef = value;
    if (value && this.viewInitialized) {
      queueMicrotask(() => this.recreateMapIfPossible());
    }
  }

  mapSession?: MapSession;
  overlayVisibility: Record<string, boolean> = {};
  overlayOpacity: Record<string, number> = {};
  overlayRenderStatuses: OverlayRenderStatus[] = [];
  restoreNotice = '';

  private mapRef: Map | null = null;
  private activeMapContainer: HTMLDivElement | null = null;
  private activeBasemapId: string | null = null;
  private activeCenterKey: string | null = null;
  private mapContainerRef?: ElementRef<HTMLDivElement>;
  private viewInitialized = false;
  private mapPreparing = false;

  constructor(private readonly changeDetector: ChangeDetectorRef) {}

  get hasCenter(): boolean {
    return Number.isFinite(this.mapSession?.center?.latitude)
      && Number.isFinite(this.mapSession?.center?.longitude);
  }

  get overlays(): OverlayEntry[] {
    return this.mapSession?.overlays || [];
  }

  get complianceWarnings(): string[] {
    return this.mapSession?.compliance_warnings || [];
  }

  get metadataOnlyOverlays(): OverlayEntry[] {
    const metadataOnlyIds = new Set(
      this.overlayRenderStatuses
        .filter((status) => status.status === 'metadata-only')
        .map((status) => status.overlayId),
    );
    return this.overlays.filter((overlay) => metadataOnlyIds.has(overlay.id));
  }

  get attributionEntries(): string[] {
    const entries = this.overlays
      .map((overlay) => overlay.attribution || overlay.provider)
      .filter((value): value is string => typeof value === 'string' && value.trim().length > 0);
    return Array.from(new Set(entries));
  }

  get legendEntries(): Array<{ id: string; label: string; mode: string }> {
    return this.overlays.map((overlay) => ({
      id: overlay.id,
      label: overlay.label,
      mode: String(overlay.rendering_mode || overlay.type || 'overlay'),
    }));
  }

  get failedOverlayStatuses(): OverlayRenderStatus[] {
    return this.overlayRenderStatuses.filter((status) => status.status === 'failed');
  }

  ngAfterViewInit(): void {
    this.viewInitialized = true;
    if (!this.mapSession && this.payload) {
      this.syncSessionFromPayload();
      this.rebuildOverlayStateFromSession();
      this.changeDetector.detectChanges();
    }
    this.recreateMapIfPossible();
    this.applyOverlayStateToMap();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['payload'] || changes['initialOverlayVisibility'] || changes['initialOverlayOpacity']) {
      this.syncSessionFromPayload();
      this.rebuildOverlayStateFromSession();
      this.recreateMapIfPossible();
      this.applyOverlayStateToMap();
    }
  }

  ngOnDestroy(): void {
    this.destroyMap();
  }

  setOverlayVisibility(overlayId: string, checked: boolean): void {
    this.overlayVisibility = { ...this.overlayVisibility, [overlayId]: checked };
    this.emitOverlayState();
    this.applyOverlayStateToMap();
  }

  setOverlayOpacity(overlayId: string, percentValue: string): void {
    const parsed = Number(percentValue);
    if (!Number.isFinite(parsed)) {
      return;
    }
    const value = Math.min(1, Math.max(0, parsed / 100));
    this.overlayOpacity = { ...this.overlayOpacity, [overlayId]: value };
    this.emitOverlayState();
    this.applyOverlayStateToMap();
  }

  onOverlayVisibilityChange(change: OverlayVisibilityChange): void {
    this.setOverlayVisibility(change.overlayId, change.checked);
  }

  onOverlayOpacityChange(change: OverlayOpacityChange): void {
    this.setOverlayOpacity(change.overlayId, change.percentValue);
  }

  zoomIn(): boolean {
    if (!this.mapRef) {
      return false;
    }
    this.mapRef.zoomIn({ duration: 120 });
    return true;
  }

  zoomOut(): boolean {
    if (!this.mapRef) {
      return false;
    }
    this.mapRef.zoomOut({ duration: 120 });
    return true;
  }

  private syncSessionFromPayload(): void {
    const next = this.payload?.map_session;
    if (!next) {
      this.mapSession = undefined;
      this.overlayRenderStatuses = [];
      return;
    }
    const overlayIds = next.overlay_ids ?? [];
    const overlays = Array.isArray(next.overlays) && next.overlays.length > 0
      ? next.overlays
      : overlayIds.map((overlayId) => ({
        id: overlayId,
        label: overlayId,
        provider: 'manifest',
        type: 'tile',
      }));
    this.mapSession = {
      ...next,
      center: next.center ?? {
        latitude: next.resolved_location?.latitude ?? null,
        longitude: next.resolved_location?.longitude ?? null,
      },
      basemap: next.basemap ?? {
        id: next.basemap_id,
        label: next.basemap_id,
        provider: 'manifest',
      },
      overlays,
    };
    this.overlayRenderStatuses = overlays.map((overlay) => ({
      overlayId: overlay.id,
      status: 'pending',
    }));
  }

  private rebuildOverlayStateFromSession(): void {
    const overlays = this.mapSession?.overlays || [];
    const overlayIds = new Set(overlays.map((overlay) => overlay.id));
    const staleVisibilityKeys = Object.keys(this.initialOverlayVisibility).filter((key) => !overlayIds.has(key));
    const staleOpacityKeys = Object.keys(this.initialOverlayOpacity).filter((key) => !overlayIds.has(key));
    const staleIds = new Set([...staleVisibilityKeys, ...staleOpacityKeys]);

    this.restoreNotice = staleIds.size > 0
      ? `Some saved overlay preferences could not be restored (${staleIds.size} removed or unknown overlay id${staleIds.size === 1 ? '' : 's'}).`
      : '';

    const nextVisibility: Record<string, boolean> = {};
    overlays.forEach((overlay) => {
      nextVisibility[overlay.id] = this.overlayVisibility[overlay.id] ?? this.initialOverlayVisibility[overlay.id] ?? true;
    });
    this.overlayVisibility = recordBooleanEqual(this.overlayVisibility, nextVisibility) ? this.overlayVisibility : nextVisibility;

    const nextOpacity: Record<string, number> = {};
    overlays.forEach((overlay) => {
      const fallback = typeof overlay.default_opacity === 'number' ? overlay.default_opacity : DEFAULT_OVERLAY_OPACITY;
      nextOpacity[overlay.id] = this.overlayOpacity[overlay.id] ?? this.initialOverlayOpacity[overlay.id] ?? fallback;
    });
    this.overlayOpacity = recordNumberEqual(this.overlayOpacity, nextOpacity) ? this.overlayOpacity : nextOpacity;

    this.emitOverlayState();
  }

  private emitOverlayState(): void {
    this.overlayStateChange.emit({
      overlayVisibility: this.overlayVisibility,
      overlayOpacity: this.overlayOpacity,
    });
  }

  private recreateMapIfPossible(): void {
    const center = this.mapSession?.center;
    if (!this.viewInitialized) {
      return;
    }
    if (!Number.isFinite(center?.longitude) || !Number.isFinite(center?.latitude)) {
      this.destroyMap();
      return;
    }
    const longitude = Number(center?.longitude);
    const latitude = Number(center?.latitude);
    if (!this.mapContainerRef?.nativeElement) {
      return;
    }
    if (this.mapPreparing) {
      return;
    }

    const nextBasemapId = this.mapSession?.basemap_id || this.mapSession?.basemap?.id || null;
    const nextCenterKey = `${latitude.toFixed(5)}:${longitude.toFixed(5)}`;
    if (this.mapRef && this.activeBasemapId === nextBasemapId && this.activeCenterKey === nextCenterKey) {
      // Overlay and metadata updates are applied to the known-good map in place.
      removeOverlayLayers(this.mapRef, this.mapSession);
      this.overlayRenderStatuses = addOverlayLayers(this.mapRef, this.mapSession);
      this.applyOverlayStateToMap();
      this.emitRenderState('ready');
      this.changeDetector.detectChanges();
      return;
    }

    const originalContainer = this.mapContainerRef.nativeElement;
    const candidateContainer = this.mapRef
      ? this.createCandidateContainer(originalContainer)
      : originalContainer;
    const previousMap = this.mapRef;
    const previousContainer = this.activeMapContainer;
    this.emitRenderState('preparing');
    this.mapPreparing = true;
    let candidateFailed = false;
    let candidate: Map;
    try {
      candidate = new maplibregl.Map({
      container: candidateContainer,
      style: this.mapSession?.basemap?.style_url || buildStyle(this.mapSession),
      center: [longitude, latitude],
      zoom: 12,
      });
    } catch (error) {
      this.mapPreparing = false;
      this.removeCandidateContainer(candidateContainer, originalContainer);
      this.emitRenderState('failed', this.safeRenderError(error));
      return;
    }

    candidate.on('error', (event: unknown) => {
      if (candidateFailed) {
        return;
      }
      const error = (event as { error?: unknown } | null)?.error;
      if (error) {
        candidateFailed = true;
        this.mapPreparing = false;
        candidate.remove();
        this.removeCandidateContainer(candidateContainer, originalContainer);
        this.emitRenderState('failed', this.safeRenderError(error));
      }
    });

    candidate.on('load', () => {
      if (candidateFailed) {
        return;
      }
      candidate.resize();
      this.overlayRenderStatuses = addOverlayLayers(candidate, this.mapSession);
      const bounds = normalizeBounds(this.mapSession?.bounds);
      if (bounds) {
        candidate.fitBounds(bounds, { padding: 30, duration: 0, maxZoom: DEFAULT_MAP_FIT_MAX_ZOOM });
      }
      if (!this.hasRenderableCanvas(candidate, candidateContainer)) {
        this.mapPreparing = false;
        candidate.remove();
        this.removeCandidateContainer(candidateContainer, originalContainer);
        this.emitRenderState('failed', 'The map source loaded but produced no renderable canvas.');
        return;
      }
      this.mapPreparing = false;
      this.mapRef = candidate;
      this.activeMapContainer = candidateContainer;
      this.activeBasemapId = nextBasemapId;
      this.activeCenterKey = nextCenterKey;
      this.applyOverlayStateToMap();
      if (previousMap && previousMap !== candidate) {
        previousMap.remove();
        if (previousContainer && previousContainer !== originalContainer) {
          previousContainer.remove();
        }
      }
      this.emitRenderState('ready');
      this.changeDetector.detectChanges();
    });
  }

  private createCandidateContainer(original: HTMLDivElement): HTMLDivElement {
    const candidate = document.createElement('div');
    candidate.className = 'maplibre-container maplibre-container--candidate';
    // MapLibre adds its own `.maplibregl-map` class, which changes the
    // container from absolute positioning to a flow element. Keep the
    // candidate stacked over the known-good map with explicit inline sizing
    // until promotion (and after MapLibre initializes it).
    candidate.style.setProperty('position', 'absolute', 'important');
    candidate.style.setProperty('inset', '0', 'important');
    candidate.style.setProperty('width', '100%', 'important');
    candidate.style.setProperty('height', '100%', 'important');
    original.parentElement?.appendChild(candidate);
    return candidate;
  }

  private removeCandidateContainer(candidate: HTMLDivElement, original: HTMLDivElement): void {
    if (candidate !== original) {
      candidate.remove();
    }
  }

  private hasRenderableCanvas(map: Map, container: HTMLDivElement): boolean {
    const canvas = container.querySelector('canvas') as HTMLCanvasElement | null;
    if (!canvas) {
      // Unit-test doubles and non-DOM renderers do not expose a canvas.
      return typeof (map as unknown as { getCanvas?: () => unknown }).getCanvas !== 'function';
    }
    return canvas.width > 0 && canvas.height > 0;
  }

  private emitRenderState(state: MapRenderState, message?: string): void {
    const sessionId = this.mapSession?.session_id;
    if (sessionId) {
      this.renderStateChange.emit({ sessionId, state, message });
    }
  }

  private safeRenderError(error: unknown): string {
    if (error instanceof Error && error.message.trim()) {
      return `Map rendering failed: ${error.message}`;
    }
    return 'Map rendering failed. The previous map remains available.';
  }

  private applyOverlayStateToMap(): void {
    const map = this.mapRef;
    if (!map || !this.mapSession?.overlays?.length) {
      return;
    }

    this.mapSession.overlays.forEach((overlay) => {
      const layerId = `overlay-layer-${overlay.id}`;
      if (!map.getLayer(layerId)) {
        return;
      }
      const visible = this.overlayVisibility[overlay.id] ?? true;
      map.setLayoutProperty(layerId, 'visibility', visible ? 'visible' : 'none');
      const opacityValue = this.overlayOpacity[overlay.id] ?? overlay.default_opacity ?? DEFAULT_OVERLAY_OPACITY;
      if (overlay.type === 'point-insight') {
        map.setPaintProperty(layerId, 'circle-opacity', opacityValue);
      } else if (isGeoJsonOverlay(overlay)) {
        const geometryType = overlay.geometry_type?.toLowerCase() || '';
        const renderingMode = String(overlay.rendering_mode || overlay.type).toLowerCase();
        if (geometryType.includes('point') || renderingMode === 'camera-points' || renderingMode === 'clustered-points') {
          map.setPaintProperty(layerId, 'circle-opacity', opacityValue);
        } else if (geometryType.includes('polygon') || renderingMode === 'choropleth') {
          map.setPaintProperty(layerId, 'fill-opacity', Math.min(opacityValue, 0.55));
        } else {
          map.setPaintProperty(layerId, 'line-opacity', opacityValue);
        }
      } else if (String(overlay.rendering_mode || overlay.type).toLowerCase() === 'vector-tile') {
        map.setPaintProperty(layerId, 'fill-opacity', Math.min(opacityValue, 0.45));
      } else {
        map.setPaintProperty(layerId, 'raster-opacity', opacityValue);
      }
    });
  }

  private destroyMap(): void {
    this.mapPreparing = false;
    if (this.mapRef) {
      this.mapRef.remove();
      this.mapRef = null;
    }
    if (this.activeMapContainer && this.activeMapContainer !== this.mapContainerRef?.nativeElement) {
      this.activeMapContainer.remove();
    }
    this.activeMapContainer = null;
    this.activeBasemapId = null;
    this.activeCenterKey = null;
  }
}

<div class="map-canvas">
  <div class="map-content">
    @if (!payload?.map_session) {
      <div class="empty-state empty-state--operations">
        <div class="empty-state__card">
          <p class="empty-state__eyebrow">Map Workspace</p>
          @if (emptyMessage) {
          <p class="empty-state__message">{{ emptyMessage }}</p>
          }
        </div>
      </div>
    } @else if (!hasCenter) {
      <div class="empty-state">
        <div class="empty-state__card">
          <p class="empty-state__eyebrow">Map Workspace</p>
          <p class="empty-state__message">Map center unavailable for interactive rendering.</p>
        </div>
      </div>
    } @else {
      <div class="maplibre-wrap">
        <div #mapContainer class="maplibre-container" tabindex="0" aria-label="Interactive map"></div>

        @if (availableBasemaps.length) {
          <label class="basemap-selector">
            <span>Basemap</span>
            <select
              [value]="mapSession?.basemap_id || ''"
              aria-label="Select map basemap"
              (change)="onBasemapSelection($any($event.target).value)"
            >
              @for (basemap of availableBasemaps; track basemap.id) {
                <option [value]="basemap.id" [disabled]="basemap.render?.status === 'unavailable'">
                  {{ basemap.name }}
                </option>
              }
            </select>
          </label>
        }

        @if (isLoading) {
          <div class="map-render-progress" role="status" aria-live="polite">
            <div class="animate-spin rounded-full h-12 w-12 border-4 border-primary/20 border-t-primary"></div>
            <p class="loading-text">Keeping the current map while the update renders…</p>
          </div>
        }

        @if (!mapSession?.basemap || mapSession?.basemap?.render_status === 'unavailable') {
          <div class="metadata-panel metadata-panel--errors" role="status" aria-live="polite">
            <p><strong>Basemap unavailable.</strong> The geographic data cannot be shown on a verified base layer.</p>
          </div>
        }

        <div class="map-zoom-controls" aria-label="Map zoom controls">
          <button type="button" aria-label="Zoom in" title="Zoom in" (click)="zoomIn()">+</button>
          <button type="button" aria-label="Zoom out" title="Zoom out" (click)="zoomOut()">&minus;</button>
        </div>

        @if (overlays.length) {
          <app-overlay-controls
            [overlays]="overlays"
            [overlayVisibility]="overlayVisibility"
            [overlayOpacity]="overlayOpacity"
            [overlayRenderStatuses]="overlayRenderStatuses"
            (overlayVisibilityChange)="onOverlayVisibilityChange($event)"
            (overlayOpacityChange)="onOverlayOpacityChange($event)"
          ></app-overlay-controls>
        }

        @if (complianceWarnings.length) {
          <div class="compliance-panel">
            @for (warning of complianceWarnings; track warning) {
              <p>{{ warning }}</p>
            }
          </div>
        }

        @if (metadataOnlyOverlays.length) {
          <div class="metadata-panel" aria-label="Metadata-only layers">
            @for (overlay of metadataOnlyOverlays; track overlay.id) {
              <p>
                <strong>{{ overlay.label }}</strong> is available as metadata or setup context only.
                @if (overlay.inspections?.[0]; as inspection) {
                  <button type="button" class="metadata-panel__action" (click)="openInspection(inspection)">Inspect</button>
                }
              </p>
            }
          </div>
        }

        @if (failedOverlayStatuses.length) {
          <div class="metadata-panel metadata-panel--errors" aria-label="Failed layers">
            @for (status of failedOverlayStatuses; track status.overlayId) {
              <p><strong>{{ status.overlayId }}</strong>: {{ status.message || 'Layer failed to render.' }}</p>
            }
          </div>
        }

        @if (legendEntries.length) {
          <div class="legend-panel" aria-label="Layer legend">
            @for (entry of legendEntries; track entry.id) {
              <p>
                <span class="legend-swatch"></span>{{ entry.label }} <span>{{ entry.mode }}</span>
                @if (inspectionForOverlayId(entry.id); as inspection) {
                  <button type="button" class="metadata-panel__action" (click)="openInspection(inspection)">Inspect</button>
                }
              </p>
            }
          </div>
        }

        @if (attributionEntries.length) {
          <div class="attribution-panel" aria-label="Map attribution">
            @for (entry of attributionEntries; track entry) {
              <span>{{ entry }}</span>
            }
          </div>
        }

        @if (restoreNotice) {
          <div class="compliance-panel" role="status" aria-live="polite">
            <p>{{ restoreNotice }}</p>
          </div>
        }

        @if (selectedInspection) {
          <aside
            #inspectionPanel
            class="map-inspection-panel"
            role="dialog"
            aria-labelledby="map-inspection-panel-title"
            tabindex="-1"
          >
            <header class="map-inspection-panel__header">
              <div>
                <p class="map-inspection-panel__eyebrow">{{ selectedInspection.association }}</p>
                <h2 id="map-inspection-panel-title">{{ selectedInspection.title }}</h2>
              </div>
              <button type="button" class="map-inspection-panel__close" aria-label="Close details" title="Close details" (click)="closeInspection()">×</button>
            </header>
            @if (selectedInspection.stale) {
              <p class="map-inspection-panel__stale">Stale provider metadata</p>
            }
            <dl>
              @for (field of selectedInspection.fields; track field.key) {
                <div>
                  <dt>{{ field.label }}</dt>
                  <dd>{{ field.value ?? '—' }}{{ field.unit ? ' ' + field.unit : '' }}</dd>
                </div>
              }
            </dl>
            @if (selectedInspection.source_url && isSafeInspectionUrl(selectedInspection.source_url)) {
              <a class="map-inspection-panel__source" [href]="selectedInspection.source_url" target="_blank" rel="noopener noreferrer">Open approved source</a>
            }
            @for (warning of selectedInspection.warnings || []; track warning) {
              <p class="map-inspection-panel__warning">{{ warning }}</p>
            }
          </aside>
        }
      </div>
    }
  </div>
</div>
