// AEGIS/client/src/app/pages/settings-page.component.ts
import { CommonModule } from '@angular/common';
import { AfterViewInit, Component, ElementRef, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';

import { ModelRoleActionsComponent } from '../components/model-role-actions.component';
import { SettingsModalShellComponent } from '../components/settings-modal-shell.component';
import { AppStateStoreService } from '../core/app-state-store.service';
import { PersistedSettingsPageState } from '../core/app-state';
import {
  ModelRole,
  buildModelSelectionPayload,
  buildSelectedModelStats,
} from '../core/model-selection';
import {
  ModelCardDescriptor,
  ModelProviderMode,
  ModelSettingsResponse,
} from '../core/types';
import {
  checkOllamaHealth,
  fetchChatModels,
  fetchChatSettings,
  pullOllamaModel,
  refreshOllamaModels,
  updateChatSettings,
} from '../core/api';
import { UserFacingErrorService } from '../core/user-facing-error.service';

@Component({
  selector: 'app-settings-page',
  standalone: true,
  imports: [CommonModule, FormsModule, ModelRoleActionsComponent, SettingsModalShellComponent],
  templateUrl: './settings-page.component.html',
  styleUrl: './settings-page.component.css',
})
export class SettingsPageComponent implements OnInit, AfterViewInit, OnDestroy {
  @ViewChild('modelGridScroll', { static: false }) modelGridRef?: ElementRef<HTMLDivElement>;

  readonly state: PersistedSettingsPageState;
  settings: ModelSettingsResponse = {
    active_provider_mode: 'local',
    chat_model_provider: 'ollama',
    chat_model_name: '',
    parser_model_provider: 'ollama',
    parser_model_name: '',
    agent_model_provider: 'ollama',
    agent_model_name: '',
    ollama_url: 'http://localhost:11434',
    openai_base_url: null,
    google_base_url: null,
    credentials: {},
  };

  cloudModels: ModelCardDescriptor[] = [];
  localModels: ModelCardDescriptor[] = [];

  providerMode: ModelProviderMode;
  searchText: string;
  statusText: string;
  isLoadingModels = false;

  isKeysModalOpen = false;
  isOllamaModalOpen = false;
  openaiKey = '';
  googleKey = '';
  ollamaUrlDraft = 'http://localhost:11434';
  keysModalStatusText = '';
  ollamaModalStatusText = '';
  keyValidationErrors: { openai?: string; google?: string } = {};

  providerFilter: 'all' | 'ollama' | 'openai' | 'google' = 'all';
  showLocalOnly = false;

  constructor(
    private readonly router: Router,
    private readonly appStateStore: AppStateStoreService,
    private readonly userFacingErrorService: UserFacingErrorService,
  ) {
    this.state = this.appStateStore.getSettingsPage();
    const query = new URLSearchParams(window.location.search);
    this.searchText = query.get('q') ?? this.state.searchText;
    const queryMode = query.get('mode');
    this.providerMode = queryMode === 'cloud' || queryMode === 'local' ? queryMode : this.state.providerMode;
    this.statusText = this.state.statusText;
  }

  ngOnInit(): void {
    void this.loadData();
    this.syncState();
  }

  ngAfterViewInit(): void {
    window.scrollTo({ top: this.state.scrollY, behavior: 'auto' });
    if (this.modelGridRef?.nativeElement) {
      this.modelGridRef.nativeElement.scrollTop = this.state.modelGridScrollTop;
    }
  }

  ngOnDestroy(): void {
    this.syncState();
  }

  get displayedModels(): ModelCardDescriptor[] {
    const localModelIds = new Set(this.localModels.map((item) => item.id));

    const source = (() => {
      if (this.providerFilter === 'all') {
        return [...this.cloudModels];
      }
      if (this.providerFilter === 'ollama') {
        return [...this.cloudModels.filter((model) => model.provider === 'ollama')];
      }
      return this.cloudModels.filter((model) => model.provider === this.providerFilter);
    })();

    const query = this.searchText.trim().toLowerCase();
    return source.filter((model) => {
      if (this.providerFilter === 'ollama' && this.showLocalOnly && !localModelIds.has(model.id)) {
        return false;
      }
      if (!query) {
        return true;
      }
      return model.name.toLowerCase().includes(query)
        || model.description.toLowerCase().includes(query)
        || model.provider.toLowerCase().includes(query);
    });
  }

  get groupedDisplayedModels(): Record<string, ModelCardDescriptor[]> {
    return this.displayedModels.reduce<Record<string, ModelCardDescriptor[]>>((acc, model) => {
      const key = model.provider.toLowerCase();
      if (!acc[key]) {
        acc[key] = [];
      }
      acc[key].push(model);
      return acc;
    }, {});
  }

  get providerKeys(): string[] {
    return Object.keys(this.groupedDisplayedModels);
  }

  get hasDisplayedModels(): boolean {
    return this.displayedModels.length > 0;
  }

  get localModelIds(): Set<string> {
    return new Set(this.localModels.map((item) => item.id));
  }

  get selectedModelStats(): Array<{ model: string; provider: string; local: boolean; assignedRoles: string[] }> {
    return buildSelectedModelStats(this.settings, this.localModelIds);
  }

  get visibleStatusText(): string {
    return this.userFacingErrorService.normalizeDisplayText(this.statusText);
  }

  get visibleOllamaModalStatusText(): string {
    return this.userFacingErrorService.normalizeDisplayText(
      this.ollamaModalStatusText,
      `Unable to reach Ollama at ${this.settings.ollama_url || this.ollamaUrlDraft}. Check that the service is running and the URL is correct.`,
    );
  }

  setSearchText(value: string): void {
    this.searchText = value;
    this.syncQueryState();
    this.syncState();
  }

  setProviderFilter(filter: 'all' | 'ollama' | 'openai' | 'google'): void {
    this.providerFilter = filter;
    if (filter !== 'ollama') {
      this.showLocalOnly = false;
    }
    this.syncState();
  }

  setShowLocalOnly(checked: boolean): void {
    this.showLocalOnly = checked;
  }

  onLocalOnlyChange(event: Event): void {
    const target = event.target as HTMLInputElement | null;
    this.setShowLocalOnly(Boolean(target?.checked));
  }

  async applyModelSelection(role: ModelRole, model: ModelCardDescriptor): Promise<void> {
    const payload = buildModelSelectionPayload(this.settings, role, model);
    try {
      const updated = await updateChatSettings(payload);
      this.settings = updated;
      this.providerMode = updated.active_provider_mode;
      this.statusText = model.provider === 'ollama'
        ? `Selected ${model.name} for ${role}`
        : `Selected ${model.name} for parser, chat, and agent`;
      this.syncQueryState();
      this.syncState();
    } catch (error: unknown) {
      this.statusText = this.userFacingErrorService.toUserFacingError(error, `Could not select ${model.name} for ${role}.`);
    }
  }

  async saveKeys(): Promise<void> {
    this.keyValidationErrors = this.validateKeyInputs();
    if (this.keyValidationErrors.openai || this.keyValidationErrors.google) {
      this.keysModalStatusText = 'Fix the highlighted API key fields before saving.';
      return;
    }

    try {
      const updated = await updateChatSettings({
        ...this.settings,
        credentials: {
          openai: this.openaiKey.trim() ? { api_key: this.openaiKey.trim() } : {},
          google: this.googleKey.trim() ? { api_key: this.googleKey.trim() } : {},
        },
      });
      this.settings = updated;
      this.openaiKey = '';
      this.googleKey = '';
      this.statusText = 'API keys saved';
      this.keysModalStatusText = 'API keys saved';
      this.isKeysModalOpen = false;
      this.syncState();
    } catch (error: unknown) {
      const detail = this.userFacingErrorService.toUserFacingError(error, 'Could not save API keys right now.');
      this.statusText = detail;
      this.keysModalStatusText = detail;
    }
  }

  async checkOllamaConnection(): Promise<void> {
    try {
      const health = await checkOllamaHealth();
      const summary = this.formatOllamaHealthSummary(health);
      this.ollamaModalStatusText = summary;
      this.statusText = `Ollama: ${summary}`;
      this.syncState();
    } catch (error: unknown) {
      const detail = this.getOllamaFailureMessage(error);
      this.statusText = detail;
      this.ollamaModalStatusText = detail;
    }
  }

  async refreshOllamaLibrary(): Promise<void> {
    try {
      await refreshOllamaModels();
      await this.loadData();
      this.statusText = 'Ollama library refreshed';
      this.ollamaModalStatusText = 'Model library refreshed.';
      this.syncState();
    } catch (error: unknown) {
      const detail = this.getOllamaFailureMessage(error);
      this.statusText = detail;
      this.ollamaModalStatusText = detail;
    }
  }

  async saveOllamaSettings(): Promise<void> {
    try {
      const updated = await updateChatSettings({
        ...this.settings,
        ollama_url: this.ollamaUrlDraft.trim() || 'http://localhost:11434',
      });
      this.settings = updated;
      this.ollamaUrlDraft = updated.ollama_url;
      this.statusText = 'Ollama settings saved';
      this.ollamaModalStatusText = 'Ollama settings saved.';
      this.isOllamaModalOpen = false;
      this.syncState();
    } catch (error: unknown) {
      const detail = this.getOllamaFailureMessage(error);
      this.statusText = detail;
      this.ollamaModalStatusText = detail;
    }
  }

  async pullLocalModel(model: ModelCardDescriptor): Promise<void> {
    try {
      await pullOllamaModel(model.name);
      await refreshOllamaModels();
      await this.loadData();
      this.statusText = `Pulled ${model.name}`;
      this.syncState();
    } catch (error: unknown) {
      this.statusText = this.userFacingErrorService.toUserFacingError(error, `Could not pull ${model.name}.`);
    }
  }

  navigateBack(): void {
    this.syncState();
    this.router.navigateByUrl('/');
  }

  closeModal(): void {
    this.isKeysModalOpen = false;
    this.isOllamaModalOpen = false;
    this.keysModalStatusText = '';
    this.ollamaModalStatusText = '';
    this.keyValidationErrors = {};
  }

  onModelGridScroll(event: Event): void {
    this.state.modelGridScrollTop = (event.target as HTMLDivElement).scrollTop;
    this.syncState();
  }

  openAiConfigured(): boolean {
    return Boolean(this.settings.credentials['openai']?.['api_key']);
  }

  googleConfigured(): boolean {
    return Boolean(this.settings.credentials['google']?.['api_key']);
  }

  private validateKeyInputs(): { openai?: string; google?: string } {
    const errors: { openai?: string; google?: string } = {};
    const openAiValue = this.openaiKey.trim();
    const googleValue = this.googleKey.trim();

    if (openAiValue && !openAiValue.startsWith('sk-')) {
      errors.openai = 'OpenAI key must start with "sk-".';
    }

    if (googleValue && !googleValue.startsWith('AIza')) {
      errors.google = 'Google key must start with "AIza".';
    }

    return errors;
  }

  private async loadData(): Promise<void> {
    this.isLoadingModels = true;
    try {
      const [nextSettings, modelLibrary] = await Promise.all([
        fetchChatSettings(),
        fetchChatModels(),
      ]);
      this.settings = nextSettings;
      this.providerMode = nextSettings.active_provider_mode;
      this.ollamaUrlDraft = nextSettings.ollama_url;
      this.cloudModels = modelLibrary.cloud;
      this.localModels = modelLibrary.local;
      this.syncQueryState();
      this.syncState();
    } catch (error: unknown) {
      this.statusText = this.userFacingErrorService.toUserFacingError(error, 'Could not load model settings right now.');
      this.syncState();
    } finally {
      this.isLoadingModels = false;
    }
  }

  private syncQueryState(): void {
    const params = new URLSearchParams(window.location.search);
    if (this.searchText.trim()) {
      params.set('q', this.searchText);
    } else {
      params.delete('q');
    }

    if (this.providerMode !== 'local') {
      params.set('mode', this.providerMode);
    } else {
      params.delete('mode');
    }

    const nextQuery = params.toString();
    const nextUrl = `${window.location.pathname}${nextQuery ? `?${nextQuery}` : ''}`;
    window.history.replaceState(window.history.state, '', nextUrl);
  }

  private syncState(): void {
    const next: PersistedSettingsPageState = {
      searchText: this.searchText,
      providerMode: this.providerMode,
      statusText: this.statusText,
      scrollY: window.scrollY,
      modelGridScrollTop: this.modelGridRef?.nativeElement.scrollTop ?? this.state.modelGridScrollTop,
    };
    this.appStateStore.updateSettingsPage(next);
  }

  private getOllamaFailureMessage(error: unknown): string {
    return this.userFacingErrorService.toUserFacingError(
      error,
      `Unable to reach Ollama at ${this.settings.ollama_url || this.ollamaUrlDraft}. Check that the service is running and the URL is correct.`,
    );
  }

  private formatOllamaHealthSummary(health: { ok?: unknown; detail?: unknown }): string {
    if (Boolean(health.ok)) {
      return 'Connection is healthy.';
    }

    const detail = typeof health.detail === 'string' ? health.detail : 'an unknown status';
    if (this.userFacingErrorService.isLowLevelConnectionError(detail)) {
      return `Unable to reach Ollama at ${this.settings.ollama_url || this.ollamaUrlDraft}. Check that the service is running and the URL is correct.`;
    }
    return `Connection check returned ${detail}.`;
  }
}

<div class="settings-page">
  <header class="settings-page__header">
    <div class="settings-page__heading">
      <h1>Model Settings</h1>
      <p>Configure active providers and assign dedicated parser, agent, and chat models.</p>
    </div>
    <div class="settings-page__header-actions">
      <button class="settings-icon-button" type="button" aria-label="Open Ollama settings" title="Ollama settings" (click)="ollamaModalStatusText = ''; isOllamaModalOpen = true">
        <span class="settings-icon-button__glyph" aria-hidden="true">
          <svg viewBox="0 0 24 24" width="15" height="15" focusable="false">
            <path d="M5 4h14a1 1 0 0 1 1 1v11a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4V5a1 1 0 0 1 1-1zm1 2v10a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V6H6zm4 2h4a1 1 0 1 1 0 2h-4a1 1 0 1 1 0-2z" fill="currentColor" />
          </svg>
        </span>
      </button>

      <button class="settings-icon-button" type="button" aria-label="Manage API keys" title="API key settings" (click)="keysModalStatusText = ''; keyValidationErrors = {}; isKeysModalOpen = true">
        <span class="settings-icon-button__glyph" aria-hidden="true">
          <svg viewBox="0 0 24 24" width="15" height="15" focusable="false">
            <path d="M14 3a7 7 0 1 0 5.5 11.3L23 17.8V21h-3v-2h-2v-2h-2.2A7 7 0 0 0 14 3zm0 2a5 5 0 1 1 0 10 5 5 0 0 1 0-10z" fill="currentColor" />
          </svg>
        </span>
      </button>

      <button type="button" class="settings-page__back" (click)="navigateBack()" aria-label="Back to chat" title="Back to chat">
        <span class="settings-page__back-icon" aria-hidden="true">←</span>
      </button>
    </div>
  </header>

  <div class="settings-page__content">
    <div class="settings-page__layout">
      <section class="settings-page__left-column">
        <section class="settings-page__controls settings-page__controls--navbar" aria-label="Settings controls">
          <div class="settings-page__controls-left">
            <div class="provider-filter-toggle provider-toggle" role="group" aria-label="Model provider filter">
              <button type="button" [class.active]="providerFilter === 'all'" (click)="setProviderFilter('all')">All</button>
              <button type="button" [class.active]="providerFilter === 'ollama'" (click)="setProviderFilter('ollama')">Ollama</button>
              <button type="button" [class.active]="providerFilter === 'openai'" (click)="setProviderFilter('openai')">OpenAI</button>
              <button type="button" [class.active]="providerFilter === 'google'" (click)="setProviderFilter('google')">Google</button>
            </div>

            @if (providerFilter === 'ollama') {
              <label class="settings-page__local-filter">
                <input type="checkbox" [checked]="showLocalOnly" (change)="onLocalOnlyChange($event)" />
                <span>Select all available</span>
              </label>
            }
          </div>

          <div class="settings-page__controls-right">
            <button type="button" class="settings-page__refresh" aria-label="Refresh from Ollama API" title="Refresh from Ollama API" (click)="refreshOllamaLibrary()">
              <svg viewBox="0 0 24 24" width="15" height="15" aria-hidden="true" focusable="false">
                <path d="M12 4V1L8 5l4 4V6a6 6 0 0 1 6 6 6 6 0 0 1-6 6 6 6 0 0 1-6-6H4a8 8 0 0 0 8 8 8 8 0 0 0 8-8 8 8 0 0 0-8-8z" fill="currentColor" />
              </svg>
            </button>
            <input class="model-search-bar" placeholder="Search models" [ngModel]="searchText" (ngModelChange)="setSearchText($event)" />
          </div>
        </section>

        <div #modelGridScroll class="model-grid-scroll" (scroll)="onModelGridScroll($event)">
          @if (isLoadingModels) {
            <section class="settings-empty-state" aria-live="polite">
              <h2>Loading model catalog</h2>
              <p>Fetching model assignments and provider metadata.</p>
            </section>
          } @else if (!hasDisplayedModels) {
            <section class="settings-empty-state" aria-live="polite">
              <h2>No models match this filter</h2>
              <p>Adjust the provider tabs or search query to show available models.</p>
            </section>
          } @else {
            @for (provider of providerKeys; track provider) {
              <section class="model-grid-provider">
                @if (providerKeys.length > 1) {
                  <header class="model-grid-provider__separator">
                    <span></span>
                    <p>{{ provider }}</p>
                  </header>
                }
                <div class="model-grid">
                  @for (model of groupedDisplayedModels[provider]; track model.provider + ':' + model.id) {
                    <article class="model-card" [class.model-card--local]="localModelIds.has(model.id)">
                      <header>
                        <h3>{{ model.name }}</h3>
                        @if (model.provider === 'ollama' && !localModelIds.has(model.id)) {
                          <button type="button" class="model-card__pull" (click)="pullLocalModel(model)" [attr.aria-label]="'Pull ' + model.name" title="Pull model">
                            <svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true" focusable="false">
                              <path d="M12 3.5a1 1 0 0 1 1 1v8l2.7-2.7a1 1 0 1 1 1.4 1.4l-4.4 4.4a1 1 0 0 1-1.4 0l-4.4-4.4a1 1 0 0 1 1.4-1.4L11 12.5v-8a1 1 0 0 1 1-1zm-6 14h12a1 1 0 1 1 0 2H6a1 1 0 1 1 0-2z" fill="currentColor" />
                            </svg>
                          </button>
                        }
                      </header>

                      <p>{{ model.description }}</p>

                      <app-model-role-actions
                        [model]="model"
                        [settings]="settings"
                        (selectRole)="applyModelSelection($event, model)"
                      ></app-model-role-actions>
                    </article>
                  }
                </div>
              </section>
            }
          }
        </div>
      </section>

      <aside class="settings-page__right-column" aria-label="Model statistics">
        <div class="settings-page__stats-table-wrap">
          <table class="settings-page__stats-table">
            <thead>
              <tr>
                <th scope="col">Model</th>
                <th scope="col">Provider</th>
                <th scope="col">Local</th>
                <th scope="col">Assigned</th>
              </tr>
            </thead>
            <tbody>
              @if (selectedModelStats.length === 0) {
                <tr>
                  <td colSpan="4">No models selected yet.</td>
                </tr>
              }
              @for (row of selectedModelStats; track row.provider + ':' + row.model) {
                <tr>
                  <td>{{ row.model }}</td>
                  <td>{{ row.provider }}</td>
                  <td>{{ row.local ? 'Yes' : 'No' }}</td>
                  <td>{{ row.assignedRoles.join(', ') }}</td>
                </tr>
              }
            </tbody>
          </table>
        </div>

        <div class="settings-page__stats-mobile-list" aria-label="Model statistics mobile">
          @if (selectedModelStats.length === 0) {
            <article class="settings-page__stats-mobile-card">
              <p class="settings-page__stats-mobile-empty">No models selected yet.</p>
            </article>
          }
          @for (row of selectedModelStats; track row.provider + ':' + row.model) {
            <article class="settings-page__stats-mobile-card">
              <h3>{{ row.model }}</h3>
              <dl>
                <div>
                  <dt>Provider</dt>
                  <dd>{{ row.provider }}</dd>
                </div>
                <div>
                  <dt>Local</dt>
                  <dd>{{ row.local ? 'Yes' : 'No' }}</dd>
                </div>
                <div>
                  <dt>Assigned</dt>
                  <dd>{{ row.assignedRoles.join(', ') }}</dd>
                </div>
              </dl>
            </article>
          }
        </div>
      </aside>
    </div>
    <footer class="settings-page__status">{{ visibleStatusText }}</footer>
  </div>

  @if (isKeysModalOpen) {
    <app-settings-modal-shell title="API keys" ariaLabel="API key management" (requestClose)="closeModal()">
      <form class="settings-modal__form" (ngSubmit)="saveKeys()">
        <div class="settings-modal__body">
          <label>
            OpenAI API key {{ openAiConfigured() ? '(Configured)' : '(Not configured)' }}
            <input type="password" autocomplete="off" [ngModel]="openaiKey" (ngModelChange)="openaiKey = $event; keyValidationErrors.openai = undefined" name="openai_api_key" placeholder="sk-..." [class.input-invalid]="!!keyValidationErrors.openai" />
            @if (keyValidationErrors.openai) {
              <span class="settings-modal__field-error">{{ keyValidationErrors.openai }}</span>
            }
          </label>
          <label>
            Google API key {{ googleConfigured() ? '(Configured)' : '(Not configured)' }}
            <input type="password" autocomplete="off" [ngModel]="googleKey" (ngModelChange)="googleKey = $event; keyValidationErrors.google = undefined" name="google_api_key" placeholder="AIza..." [class.input-invalid]="!!keyValidationErrors.google" />
            @if (keyValidationErrors.google) {
              <span class="settings-modal__field-error">{{ keyValidationErrors.google }}</span>
            }
          </label>
          @if (keysModalStatusText) {
            <p class="settings-modal__status" aria-live="polite">{{ keysModalStatusText }}</p>
          }
        </div>
        <footer class="settings-modal__footer">
          <button type="submit" class="primary-button">Save keys</button>
        </footer>
      </form>
    </app-settings-modal-shell>
  }

  @if (isOllamaModalOpen) {
    <app-settings-modal-shell title="Ollama settings" ariaLabel="Ollama settings" (requestClose)="closeModal()">
      <form class="settings-modal__form" (ngSubmit)="saveOllamaSettings()">
        <div class="settings-modal__body">
          <label>
            Ollama server URL
            <input [ngModel]="ollamaUrlDraft" (ngModelChange)="ollamaUrlDraft = $event" name="ollama_server_url" />
          </label>
          @if (visibleOllamaModalStatusText) {
            <p class="settings-modal__status" aria-live="polite">{{ visibleOllamaModalStatusText }}</p>
          }
        </div>
        <footer class="settings-modal__footer settings-modal__footer--spread">
          <div class="row-actions">
            <button type="button" (click)="checkOllamaConnection()">Check connection</button>
            <button type="button" (click)="refreshOllamaLibrary()">Refresh models</button>
          </div>
          <button type="submit" class="primary-button">Save settings</button>
        </footer>
      </form>
    </app-settings-modal-shell>
  }
</div>

// AEGIS/client/src/pages/SettingsPage.tsx
import { ReactNode, useCallback, useEffect, useMemo, useRef, useState } from 'react';

import ModelGrid from '../components/settings/ModelGrid';
import CredentialField from '../components/settings/CredentialField';
import SettingsIconButton from '../components/settings/SettingsIconButton';
import ModelProviderToggle from '../components/settings/ModelProviderToggle';
import ModelSearchBar from '../components/settings/ModelSearchBar';
import SettingsModal from '../components/settings/SettingsModal';
import './SettingsPage.css';
import { PersistedSettingsPageState } from '../state/appState';
import { useActivePagePersistence } from '../hooks/useActivePagePersistence';
import { useSettingsData } from '../hooks/useSettingsData';
import { useSettingsQueryState } from '../hooks/useSettingsQueryState';

interface SettingsPageProps {
    onBack: () => void;
    state: PersistedSettingsPageState;
    onStateChange: (state: PersistedSettingsPageState) => void;
    isActive: boolean;
}

function SettingsPage({ onBack, state, onStateChange, isActive }: SettingsPageProps) {
    const {
        settings,
        cloudModels,
        localModels,
        providerMode,
        statusText,
        ollamaUrlDraft,
        setProviderMode,
        setOllamaUrlDraft,
        applyModelSelection,
        saveKeys,
        checkOllamaConnection,
        refreshOllamaLibrary,
        saveOllamaSettings,
        pullLocalModel,
    } = useSettingsData(state.statusText);
    const [providerModeInitialized, setProviderModeInitialized] = useState(false);
    const { searchText, setSearchText, initialProviderMode } = useSettingsQueryState({
        initialSearchText: state.searchText,
        providerMode,
        isActive,
    });
    const modelGridRef = useRef<HTMLDivElement | null>(null);
    const [isKeysModalOpen, setIsKeysModalOpen] = useState(false);
    const [isOllamaModalOpen, setIsOllamaModalOpen] = useState(false);
    const [openaiKey, setOpenaiKey] = useState('');
    const [googleKey, setGoogleKey] = useState('');
    const [providerFilter, setProviderFilter] = useState<'all' | 'ollama' | 'openai' | 'google'>('all');
    const [showLocalOnly, setShowLocalOnly] = useState(false);

    useEffect(() => {
        if (providerModeInitialized) {
            return;
        }
        setProviderMode(initialProviderMode || state.providerMode);
        setProviderModeInitialized(true);
    }, [providerModeInitialized, initialProviderMode, setProviderMode, state.providerMode]);

    useEffect(() => {
        if (providerFilter !== 'ollama' && showLocalOnly) {
            setShowLocalOnly(false);
        }
    }, [providerFilter, showLocalOnly]);

    const buildState = useCallback((scrollY: number): PersistedSettingsPageState => ({
        searchText,
        providerMode,
        statusText,
        scrollY,
        modelGridScrollTop: modelGridRef.current?.scrollTop ?? state.modelGridScrollTop,
    }), [searchText, providerMode, statusText, state.modelGridScrollTop]);

    const restoreState = useCallback(() => {
        window.scrollTo({ top: state.scrollY, behavior: 'auto' });
        if (modelGridRef.current) {
            modelGridRef.current.scrollTop = state.modelGridScrollTop;
        }
    }, [state.scrollY, state.modelGridScrollTop]);

    useActivePagePersistence({
        isActive,
        state,
        onStateChange,
        buildState,
        restoreState,
        syncDeps: [searchText, providerMode, statusText, state.modelGridScrollTop],
    });

    const localModelIds = useMemo(() => new Set(localModels.map((item) => item.id)), [localModels]);
    const selectedModelStats = useMemo(() => {
        const rows = new Map<string, { model: string; provider: string; local: boolean; assignedRoles: string[] }>();
        const assignments = [
            { role: 'Parser', provider: settings.parser_model_provider, name: settings.parser_model_name },
            { role: 'Chat', provider: settings.chat_model_provider, name: settings.chat_model_name },
            { role: 'Agent', provider: settings.agent_model_provider, name: settings.agent_model_name },
        ];

        assignments.forEach(({ role, provider, name }) => {
            const normalizedProvider = provider.trim();
            const normalizedName = name.trim();
            if (!normalizedProvider || !normalizedName) {
                return;
            }
            const key = `${normalizedProvider}:${normalizedName}`;
            const existing = rows.get(key);
            const local = localModelIds.has(normalizedName);
            if (existing) {
                existing.local = existing.local || local;
                if (!existing.assignedRoles.includes(role)) {
                    existing.assignedRoles.push(role);
                }
                return;
            }
            rows.set(key, {
                model: normalizedName,
                provider: normalizedProvider,
                local,
                assignedRoles: [role],
            });
        });

        return Array.from(rows.values());
    }, [
        settings.parser_model_provider,
        settings.parser_model_name,
        settings.chat_model_provider,
        settings.chat_model_name,
        settings.agent_model_provider,
        settings.agent_model_name,
        localModelIds,
    ]);

    const displayedModels = useMemo(() => {
        const source = (() => {
            if (providerFilter === 'all') {
                return [...cloudModels];
            }
            if (providerFilter === 'ollama') {
                return [...cloudModels.filter((model) => model.provider === 'ollama')];
            }
            return cloudModels.filter((model) => model.provider === providerFilter);
        })();
        const query = searchText.trim().toLowerCase();
        return source.filter((model) => {
            if (providerFilter === 'ollama' && showLocalOnly && !localModelIds.has(model.id)) {
                return false;
            }
            if (!query) {
                return true;
            }
            return (
                model.name.toLowerCase().includes(query)
                || model.description.toLowerCase().includes(query)
                || model.provider.toLowerCase().includes(query)
            );
        });
    }, [providerFilter, cloudModels, searchText, localModelIds, showLocalOnly]);

    const keysFooter: ReactNode = (
        <button
            type="button"
            className="primary-button"
            onClick={async () => {
                await saveKeys(openaiKey, googleKey);
                setOpenaiKey('');
                setGoogleKey('');
                setIsKeysModalOpen(false);
            }}
        >
            Save keys
        </button>
    );

    const ollamaFooter: ReactNode = (
        <>
            <div className="row-actions">
                <button
                    type="button"
                    onClick={async () => {
                        await checkOllamaConnection();
                    }}
                >
                    Check connection
                </button>
                <button
                    type="button"
                    onClick={async () => {
                        await refreshOllamaLibrary();
                    }}
                >
                    Refresh models
                </button>
            </div>
            <button
                type="button"
                className="primary-button"
                onClick={async () => {
                    await saveOllamaSettings();
                    setIsOllamaModalOpen(false);
                }}
            >
                Save settings
            </button>
        </>
    );

    return (
        <div className="settings-page" hidden={!isActive} aria-hidden={!isActive}>
            <header className="settings-page__header">
                <div className="settings-page__heading">
                    <h1>Model Settings</h1>
                    <p>Configure active providers and assign dedicated parser, agent, and chat models.</p>
                </div>
                <div className="settings-page__header-actions">
                    <SettingsIconButton
                        onClick={() => setIsOllamaModalOpen(true)}
                        ariaLabel="Open Ollama settings"
                        title="Ollama settings"
                        icon={(
                            <svg viewBox="0 0 24 24" width="15" height="15" focusable="false">
                                <path d="M5 4h14a1 1 0 0 1 1 1v11a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4V5a1 1 0 0 1 1-1zm1 2v10a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V6H6zm4 2h4a1 1 0 1 1 0 2h-4a1 1 0 1 1 0-2z" fill="currentColor" />
                            </svg>
                        )}
                    />
                    <SettingsIconButton
                        onClick={() => setIsKeysModalOpen(true)}
                        ariaLabel="Manage API keys"
                        title="API key settings"
                        icon={(
                            <svg viewBox="0 0 24 24" width="15" height="15" focusable="false">
                                <path d="M14 3a7 7 0 1 0 5.5 11.3L23 17.8V21h-3v-2h-2v-2h-2.2A7 7 0 0 0 14 3zm0 2a5 5 0 1 1 0 10 5 5 0 0 1 0-10z" fill="currentColor" />
                            </svg>
                        )}
                    />
                    <button type="button" className="settings-page__back" onClick={onBack} aria-label="Back to chat" title="Back to chat">
                        <span className="settings-page__back-icon" aria-hidden="true">←</span>
                    </button>
                </div>
            </header>

            <div className="settings-page__content">
                <div className="settings-page__layout">
                    <section className="settings-page__left-column">
                        <section className="settings-page__controls settings-page__controls--navbar" aria-label="Settings controls">
                            <div className="settings-page__controls-left">
                                <ModelProviderToggle value={providerFilter} onChange={setProviderFilter} />
                                {providerFilter === 'ollama' && (
                                    <label className="settings-page__local-filter">
                                        <input
                                            type="checkbox"
                                            checked={showLocalOnly}
                                            onChange={(event) => setShowLocalOnly(event.target.checked)}
                                        />
                                        <span>Select all available</span>
                                    </label>
                                )}
                            </div>
                            <div className="settings-page__controls-spacer" aria-hidden="true" />
                            <div className="settings-page__controls-right">
                                <button
                                    type="button"
                                    className="settings-page__refresh"
                                    onClick={refreshOllamaLibrary}
                                    aria-label="Refresh from Ollama API"
                                    title="Refresh from Ollama API"
                                >
                                    <svg viewBox="0 0 24 24" width="15" height="15" aria-hidden="true" focusable="false">
                                        <path
                                            d="M12 4V1L8 5l4 4V6a6 6 0 0 1 6 6 6 6 0 0 1-6 6 6 6 0 0 1-6-6H4a8 8 0 0 0 8 8 8 8 0 0 0 8-8 8 8 0 0 0-8-8z"
                                            fill="currentColor"
                                        />
                                    </svg>
                                </button>
                                <ModelSearchBar value={searchText} onChange={setSearchText} />
                            </div>
                        </section>

                        <ModelGrid
                            containerRef={modelGridRef}
                            models={displayedModels}
                            localModelIds={localModelIds}
                            selectedParserModel={{
                                provider: settings.parser_model_provider,
                                name: settings.parser_model_name,
                            }}
                            selectedChatModel={{
                                provider: settings.chat_model_provider,
                                name: settings.chat_model_name,
                            }}
                            selectedAgentModel={{
                                provider: settings.agent_model_provider,
                                name: settings.agent_model_name,
                            }}
                            onSelectParser={(model) => applyModelSelection('parser', model)}
                            onSelectChat={(model) => applyModelSelection('chat', model)}
                            onSelectAgent={(model) => applyModelSelection('agent', model)}
                            onPull={async (model) => {
                                await pullLocalModel(model);
                            }}
                        />
                    </section>

                    <aside className="settings-page__right-column" aria-label="Model statistics">
                        <div className="settings-page__stats-table-wrap">
                            <table className="settings-page__stats-table">
                                <thead>
                                    <tr>
                                        <th scope="col">Model</th>
                                        <th scope="col">Provider</th>
                                        <th scope="col">Local</th>
                                        <th scope="col">Assigned</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {selectedModelStats.length === 0 && (
                                        <tr>
                                            <td colSpan={4}>No models selected yet.</td>
                                        </tr>
                                    )}
                                    {selectedModelStats.map((row) => {
                                        return (
                                            <tr key={`stats:${row.provider}:${row.model}`}>
                                                <td>{row.model}</td>
                                                <td>{row.provider}</td>
                                                <td>{row.local ? 'Yes' : 'No'}</td>
                                                <td>{row.assignedRoles.join(', ')}</td>
                                            </tr>
                                        );
                                    })}
                                </tbody>
                            </table>
                        </div>
                    </aside>
                </div>
                <footer className="settings-page__status">{statusText}</footer>
            </div>

            {isKeysModalOpen && (
                <SettingsModal
                    title="API keys"
                    ariaLabel="API key management"
                    onClose={() => setIsKeysModalOpen(false)}
                    footer={keysFooter}
                >
                    <CredentialField
                        label="OpenAI API key"
                        configured={Boolean(settings.credentials.openai?.api_key)}
                        placeholder="sk-..."
                        value={openaiKey}
                        onChange={setOpenaiKey}
                    />
                    <CredentialField
                        label="Google API key"
                        configured={Boolean(settings.credentials.google?.api_key)}
                        placeholder="AIza..."
                        value={googleKey}
                        onChange={setGoogleKey}
                    />
                </SettingsModal>
            )}

            {isOllamaModalOpen && (
                <SettingsModal
                    title="Ollama settings"
                    ariaLabel="Ollama settings"
                    onClose={() => setIsOllamaModalOpen(false)}
                    footer={ollamaFooter}
                    footerClassName="settings-modal__footer settings-modal__footer--spread"
                >
                    <label>
                        Ollama server URL
                        <input value={ollamaUrlDraft} onChange={(event) => setOllamaUrlDraft(event.target.value)} />
                    </label>
                </SettingsModal>
            )}
        </div>
    );
}

export default SettingsPage;
