// AEGIS/client/src/pages/GeospatialPage.tsx
import { useCallback, useState } from 'react';

import AgentChatPanel from '../components/chat/AgentChatPanel';
import MapPreview from '../components/MapPreview';
import { MapSession, SearchResponsePayload } from '../types';
import './GeospatialPage.css';
import { PersistedChatPageState } from '../state/appState';
import { useActivePagePersistence } from '../hooks/useActivePagePersistence';
import { useResizableToolbar } from '../hooks/useResizableToolbar';

interface GeospatialPageProps {
    onOpenSettings: () => void;
    state: PersistedChatPageState;
    onStateChange: (state: PersistedChatPageState) => void;
    isActive: boolean;
}

function GeospatialPage({ onOpenSettings, state, onStateChange, isActive }: GeospatialPageProps) {
    const [payload, setPayload] = useState<SearchResponsePayload | undefined>(state.payload);
    const [toolbarWidthState, setToolbarWidthState] = useState(state.toolbarWidth);
    const [isToolbarCollapsed, setIsToolbarCollapsed] = useState(state.isToolbarCollapsed);
    const [chatPanelState, setChatPanelState] = useState(state.chatPanel);
    const [mapState, setMapState] = useState(state.mapState);
    const [chatProgress, setChatProgress] = useState({ isLoading: false, progressPercent: 0 });

    const {
        toolbarWidth,
        isResizing,
        startResize,
    } = useResizableToolbar({
        initialWidth: toolbarWidthState,
        onWidthChange: setToolbarWidthState,
    });

    const handleMapSession = (mapSession: MapSession | undefined) => {
        if (!mapSession) {
            return;
        }
        setPayload((current) => ({
            satellite_imagery: current?.satellite_imagery,
            map_session: mapSession,
            compliance_warnings: mapSession.compliance_warnings,
        }));
    };

    const buildState = useCallback((scrollY: number): PersistedChatPageState => ({
        toolbarWidth: toolbarWidthState,
        isToolbarCollapsed,
        payload,
        chatPanel: chatPanelState,
        mapState,
        scrollY,
    }), [toolbarWidthState, isToolbarCollapsed, payload, chatPanelState, mapState]);

    const restoreState = useCallback(() => {
        window.scrollTo({ top: state.scrollY, behavior: 'auto' });
    }, [state.scrollY]);

    useActivePagePersistence({
        isActive,
        state,
        onStateChange,
        buildState,
        restoreState,
        syncDeps: [toolbarWidthState, isToolbarCollapsed, payload, chatPanelState, mapState],
    });

    return (
        <div className="geospatial-page" hidden={!isActive} aria-hidden={!isActive}>
            <div
                className={`geospatial-workspace${isToolbarCollapsed ? ' geospatial-workspace--toolbar-collapsed' : ''}`}
                style={{ ['--toolbar-width' as string]: `${toolbarWidth}px` }}
            >
                <aside className="toolbar-panel" aria-label="Chat toolbar">
                    <header className="toolbar-brand" aria-label="Application identity">
                        <div className="toolbar-brand__identity">
                            <span className="toolbar-brand__icon" aria-hidden="true">
                                <span />
                                <span />
                                <span />
                            </span>
                            <span className="toolbar-brand__logo">AEGIS</span>
                        </div>
                    </header>

                    <div className="toolbar-panel__content">
                        <AgentChatPanel
                            onMapSession={handleMapSession}
                            initialState={chatPanelState}
                            onStateChange={setChatPanelState}
                            onProgressChange={setChatProgress}
                        />
                    </div>
                </aside>

                <div
                    className={[
                        'toolbar-resize-handle',
                        isResizing ? 'is-active' : '',
                        isToolbarCollapsed ? 'is-collapsed' : ''
                    ].filter(Boolean).join(' ')}
                    aria-hidden="true"
                    onMouseDown={() => {
                        startResize(() => {
                            if (isToolbarCollapsed) {
                                setIsToolbarCollapsed(false);
                            }
                        });
                    }}
                />

                <section className="canvas-panel" aria-label="Map canvas">
                    <header className="canvas-header" aria-label="Workspace header">
                        <div className="canvas-header__actions">
                            <button type="button" className="canvas-header__icon-button" aria-label="Alerts">
                                <svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true" focusable="false">
                                    <path
                                        d="M12 3.5a4.8 4.8 0 0 0-4.8 4.8v1.7c0 .8-.2 1.6-.6 2.3L5.1 15h13.8l-1.5-2.7a4.8 4.8 0 0 1-.6-2.3V8.3A4.8 4.8 0 0 0 12 3.5zm0 17a2.4 2.4 0 0 1-2.2-1.5h4.4A2.4 2.4 0 0 1 12 20.5z"
                                        fill="currentColor"
                                    />
                                </svg>
                            </button>
                            <button
                                type="button"
                                className="canvas-header__icon-button"
                                aria-label="Workspace settings"
                                onClick={onOpenSettings}
                            >
                                <svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true" focusable="false">
                                    <path
                                        d="M19.4 13.5c.1-.5.1-1 .1-1.5s0-1-.1-1.5l2-1.5-2-3.4-2.4 1a8 8 0 0 0-2.6-1.5l-.3-2.6h-4l-.3 2.6a8 8 0 0 0-2.6 1.5l-2.4-1-2 3.4 2 1.5c-.1.5-.1 1-.1 1.5s0 1 .1 1.5l-2 1.5 2 3.4 2.4-1a8 8 0 0 0 2.6 1.5l.3 2.6h4l.3-2.6a8 8 0 0 0 2.6-1.5l2.4 1 2-3.4-2-1.5zM12 15.1a3.1 3.1 0 1 1 0-6.2 3.1 3.1 0 0 1 0 6.2z"
                                        fill="currentColor"
                                    />
                                </svg>
                            </button>
                        </div>
                    </header>
                    <div className="canvas-panel__body">
                    <MapPreview
                        payload={payload}
                        isLoading={false}
                        emptyMessage="Ask the assistant to run a geospatial search."
                        initialOverlayVisibility={mapState.overlayVisibility}
                        initialOverlayOpacity={mapState.overlayOpacity}
                        onOverlayStateChange={setMapState}
                    />
                    </div>
                </section>
                <div className="chat-progress-indicator" aria-live="polite">
                    {chatProgress.isLoading && <span className="chat-progress-spinner" aria-hidden="true" />}
                    <span>{chatProgress.progressPercent}%</span>
                </div>
            </div>
        </div>
    );
}

export default GeospatialPage;

// AEGIS/client/src/app/pages/geospatial-page.component.ts
import { CommonModule } from '@angular/common';
import { AfterViewInit, Component, ElementRef, OnDestroy, ViewChild } from '@angular/core';
import { Router } from '@angular/router';

import { MapPreviewComponent } from '../components/map-preview.component';
import { AppStateStoreService } from '../core/app-state-store.service';
import { PersistedChatPageState } from '../core/app-state';
import { MapSession, SearchResponsePayload, ChatMessage, ChatRole, ChatStreamEvent } from '../core/types';
import { streamChatTurn } from '../core/api';

@Component({
  selector: 'app-geospatial-page',
  standalone: true,
  imports: [CommonModule, MapPreviewComponent],
  templateUrl: './geospatial-page.component.html',
  styleUrl: './geospatial-page.component.css',
})
export class GeospatialPageComponent implements AfterViewInit, OnDestroy {
  @ViewChild('transcript', { static: false }) transcriptRef?: ElementRef<HTMLDivElement>;

  payload?: SearchResponsePayload;
  toolbarWidthState = 480;
  isToolbarCollapsed = false;
  mapState = { overlayVisibility: {}, overlayOpacity: {} } as PersistedChatPageState['mapState'];

  sessionId?: number;
  messages: ChatMessage[] = [];
  status = 'Idle';
  assistantDraft = '';
  composerDraft = '';
  transcriptScrollTop = 0;

  isLoading = false;
  progressPercent = 0;
  isResizing = false;

  private readonly minWidth = 280;
  private readonly maxWidth = 760;
  private readonly canvasMinWidth = 320;
  private readonly chatPageState: PersistedChatPageState;
  private mouseMoveHandler?: (event: MouseEvent) => void;
  private mouseUpHandler?: () => void;

  constructor(
    private readonly router: Router,
    private readonly appStateStore: AppStateStoreService,
  ) {
    this.chatPageState = this.appStateStore.getChatPage();
    this.payload = this.chatPageState.payload;
    this.toolbarWidthState = this.chatPageState.toolbarWidth;
    this.isToolbarCollapsed = this.chatPageState.isToolbarCollapsed;
    this.mapState = this.chatPageState.mapState;

    this.sessionId = this.chatPageState.chatPanel.sessionId;
    this.messages = this.chatPageState.chatPanel.messages;
    this.status = this.chatPageState.chatPanel.status;
    this.assistantDraft = this.chatPageState.chatPanel.assistantDraft;
    this.composerDraft = this.chatPageState.chatPanel.composerDraft;
    this.transcriptScrollTop = this.chatPageState.chatPanel.transcriptScrollTop;
  }

  ngAfterViewInit(): void {
    window.scrollTo({ top: this.chatPageState.scrollY, behavior: 'auto' });
    if (this.transcriptRef?.nativeElement) {
      this.transcriptRef.nativeElement.scrollTop = this.transcriptScrollTop;
    }
  }

  ngOnDestroy(): void {
    this.stopResize();
    this.syncState();
  }

  get toolbarWidth(): number {
    return this.toolbarWidthState;
  }

  get renderedMessages(): ChatMessage[] {
    if (!this.assistantDraft.trim()) {
      return this.messages;
    }
    return [...this.messages, { role: 'assistant' as ChatRole, content: this.assistantDraft }];
  }

  navigateToSettings(): void {
    this.syncState();
    this.router.navigateByUrl('/settings');
  }

  startResize(): void {
    if (this.isToolbarCollapsed) {
      this.isToolbarCollapsed = false;
    }
    this.isResizing = true;

    this.mouseMoveHandler = (event: MouseEvent) => {
      const viewportWidth = window.innerWidth;
      const maxAllowedByViewport = viewportWidth - this.canvasMinWidth;
      const clamped = this.clampToolbarWidth(Math.min(event.clientX, maxAllowedByViewport));
      this.toolbarWidthState = clamped;
      this.syncState();
    };

    this.mouseUpHandler = () => {
      this.stopResize();
    };

    window.addEventListener('mousemove', this.mouseMoveHandler);
    window.addEventListener('mouseup', this.mouseUpHandler);
  }

  onTranscriptScroll(event: Event): void {
    this.transcriptScrollTop = (event.target as HTMLDivElement).scrollTop;
    this.syncState();
  }

  onComposerChange(value: string): void {
    this.composerDraft = value;
    this.syncState();
  }

  onComposerKeydown(event: KeyboardEvent): void {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      void this.sendMessage();
    }
  }

  onOverlayStateChange(state: { overlayVisibility: Record<string, boolean>; overlayOpacity: Record<string, number> }): void {
    this.mapState = state;
    this.syncState();
  }

  async sendMessage(): Promise<void> {
    const trimmed = this.composerDraft.trim();
    if (!trimmed || this.isLoading) {
      return;
    }

    const message = trimmed;
    this.composerDraft = '';
    this.isLoading = true;
    this.status = 'Submitting';
    this.progressPercent = 8;
    this.messages = [...this.messages, { role: 'user', content: message }];
    this.assistantDraft = '';
    this.syncState();

    try {
      await streamChatTurn(
        {
          session_id: this.sessionId,
          message,
        },
        (event) => this.pushEvent(event),
      );
    } catch (error: unknown) {
      const fallback = String((error as { message?: string })?.message ?? error);
      this.status = 'Failed';
      this.assistantDraft = '';
      this.messages = [...this.messages, { role: 'assistant', content: fallback }];
      this.progressPercent = 0;
    } finally {
      this.isLoading = false;
      this.syncState();
      queueMicrotask(() => this.scrollTranscriptToBottom());
    }
  }

  private pushEvent(event: ChatStreamEvent): void {
    if (event.event === 'status') {
      this.status = String(event.data.message ?? 'Running');
      this.progressPercent = Math.max(this.progressPercent, 14);
      this.syncState();
      return;
    }

    if (event.event === 'assistant_delta') {
      const delta = String(event.data.delta ?? '');
      this.assistantDraft = `${this.assistantDraft}${delta}`;
      this.progressPercent = Math.min(92, Math.max(this.progressPercent, 20 + Math.round(this.assistantDraft.length / 7)));
      this.syncState();
      return;
    }

    if (event.event === 'tool_status') {
      this.status = 'Executing tools';
      this.progressPercent = Math.max(this.progressPercent, 68);
      this.syncState();
      return;
    }

    if (event.event === 'error') {
      this.status = 'Failed';
      this.assistantDraft = '';
      this.progressPercent = 0;
      this.syncState();
      return;
    }

    if (event.event === 'final') {
      const finalMessage = String(event.data.assistant_message ?? this.assistantDraft ?? '');
      const nextSessionId = Number(event.data.session_id ?? this.sessionId ?? 0);
      const followUpRequired = Boolean(event.data.follow_up_required);
      if (nextSessionId > 0) {
        this.sessionId = nextSessionId;
      }
      this.messages = [...this.messages, { role: 'assistant', content: finalMessage }];

      const mapSession = event.data.map_session;
      if (typeof mapSession === 'object' && mapSession !== null) {
        this.handleMapSession(mapSession as MapSession);
      }
      this.assistantDraft = '';
      this.status = followUpRequired ? 'Need more detail' : 'Complete';
      this.progressPercent = 100;
      this.syncState();
      queueMicrotask(() => this.scrollTranscriptToBottom());
    }
  }

  private handleMapSession(mapSession: MapSession | undefined): void {
    if (!mapSession) {
      return;
    }
    this.payload = {
      satellite_imagery: this.payload?.satellite_imagery,
      map_session: mapSession,
      compliance_warnings: mapSession.compliance_warnings,
    };
  }

  private syncState(): void {
    const next: PersistedChatPageState = {
      toolbarWidth: this.toolbarWidthState,
      isToolbarCollapsed: this.isToolbarCollapsed,
      payload: this.payload,
      chatPanel: {
        sessionId: this.sessionId,
        messages: this.messages,
        status: this.status,
        assistantDraft: this.assistantDraft,
        composerDraft: this.composerDraft,
        transcriptScrollTop: this.transcriptRef?.nativeElement.scrollTop ?? this.transcriptScrollTop,
      },
      mapState: this.mapState,
      scrollY: window.scrollY,
    };
    this.appStateStore.updateChatPage(next);
  }

  private clampToolbarWidth(value: number): number {
    return Math.max(this.minWidth, Math.min(this.maxWidth, value));
  }

  private stopResize(): void {
    this.isResizing = false;
    if (this.mouseMoveHandler) {
      window.removeEventListener('mousemove', this.mouseMoveHandler);
      this.mouseMoveHandler = undefined;
    }
    if (this.mouseUpHandler) {
      window.removeEventListener('mouseup', this.mouseUpHandler);
      this.mouseUpHandler = undefined;
    }
  }

  private scrollTranscriptToBottom(): void {
    const container = this.transcriptRef?.nativeElement;
    if (!container) {
      return;
    }
    container.scrollTop = container.scrollHeight;
    this.transcriptScrollTop = container.scrollTop;
  }
}

<div class="geospatial-page">
  <div
    class="geospatial-workspace"
    [class.geospatial-workspace--toolbar-collapsed]="isToolbarCollapsed"
    [style.--toolbar-width.px]="toolbarWidth"
  >
    <aside class="toolbar-panel" aria-label="Chat toolbar">
      <header class="toolbar-brand" aria-label="Application identity">
        <div class="toolbar-brand__identity">
          <span class="toolbar-brand__icon" aria-hidden="true">
            <span></span>
            <span></span>
            <span></span>
          </span>
          <span class="toolbar-brand__logo">AEGIS</span>
        </div>
      </header>

      <div class="toolbar-panel__content">
        <section class="agent-chat-panel" aria-label="Agent Chat">
          <div
            #transcript
            class="chat-transcript"
            aria-live="polite"
            (scroll)="onTranscriptScroll($event)"
          >
            @for (message of renderedMessages; track $index) {
              <article class="chat-message" [class]="'chat-message chat-message--' + message.role">
                <header class="chat-message__role">{{ message.role }}</header>
                <p class="chat-message__content">{{ message.content }}</p>
              </article>
            }
          </div>

          <div class="chat-composer">
            <textarea
              aria-label="Chat message"
              [value]="composerDraft"
              (input)="onComposerChange($any($event.target).value)"
              (keydown)="onComposerKeydown($event)"
              [disabled]="isLoading"
              placeholder="Ask for a place, coordinates, or environmental overlay."
            ></textarea>
            <button
              type="button"
              class="primary-button"
              aria-label="Send"
              (click)="sendMessage()"
              [disabled]="isLoading || !composerDraft.trim()"
            >
              <span class="sr-only">Send message</span>
              <svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true" focusable="false">
                <path
                  d="M21.7 3.3a1 1 0 0 0-1-.2L3.6 9.7a1 1 0 0 0 0 1.9l7.8 2.6 2.6 7.8a1 1 0 0 0 .9.7h.1a1 1 0 0 0 .9-.6l6.8-17.8a1 1 0 0 0-.2-1zM15 18.8l-1.8-5.5 4.6-4.6-5.9 3.6-5.5-1.8L19.2 5 15 18.8z"
                  fill="currentColor"
                />
              </svg>
            </button>
          </div>
        </section>
      </div>
    </aside>

    <div
      class="toolbar-resize-handle"
      [class.is-active]="isResizing"
      [class.is-collapsed]="isToolbarCollapsed"
      aria-hidden="true"
      (mousedown)="startResize()"
    ></div>

    <section class="canvas-panel" aria-label="Map canvas">
      <header class="canvas-header" aria-label="Workspace header">
        <div class="canvas-header__actions">
          <button type="button" class="canvas-header__icon-button" aria-label="Alerts">
            <svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true" focusable="false">
              <path
                d="M12 3.5a4.8 4.8 0 0 0-4.8 4.8v1.7c0 .8-.2 1.6-.6 2.3L5.1 15h13.8l-1.5-2.7a4.8 4.8 0 0 1-.6-2.3V8.3A4.8 4.8 0 0 0 12 3.5zm0 17a2.4 2.4 0 0 1-2.2-1.5h4.4A2.4 2.4 0 0 1 12 20.5z"
                fill="currentColor"
              />
            </svg>
          </button>
          <button
            type="button"
            class="canvas-header__icon-button"
            aria-label="Open settings"
            (click)="navigateToSettings()"
          >
            <svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true" focusable="false">
              <path
                d="M19.4 13.5c.1-.5.1-1 .1-1.5s0-1-.1-1.5l2-1.5-2-3.4-2.4 1a8 8 0 0 0-2.6-1.5l-.3-2.6h-4l-.3 2.6a8 8 0 0 0-2.6 1.5l-2.4-1-2 3.4 2 1.5c-.1.5-.1 1-.1 1.5s0 1 .1 1.5l-2 1.5 2 3.4 2.4-1a8 8 0 0 0 2.6 1.5l.3 2.6h4l.3-2.6a8 8 0 0 0 2.6-1.5l2.4 1 2-3.4-2-1.5zM12 15.1a3.1 3.1 0 1 1 0-6.2 3.1 3.1 0 0 1 0 6.2z"
                fill="currentColor"
              />
            </svg>
          </button>
        </div>
      </header>
      <div class="canvas-panel__body">
        <app-map-preview
          [payload]="payload"
          [isLoading]="false"
          [emptyMessage]="'Ask the assistant to run a geospatial search.'"
          [initialOverlayVisibility]="mapState.overlayVisibility"
          [initialOverlayOpacity]="mapState.overlayOpacity"
          (overlayStateChange)="onOverlayStateChange($event)"
        ></app-map-preview>
      </div>
    </section>

    <div class="chat-progress-indicator" aria-live="polite">
      @if (isLoading) {
        <span class="chat-progress-spinner" aria-hidden="true"></span>
      }
      <span>{{ progressPercent }}%</span>
    </div>
  </div>
</div>
